// Generated by CoffeeScript 1.9.3
(function() {
  var WildberryPrincess, chai, sinon, sinonChai;

  if (typeof require !== "undefined" && require !== null) {
    sinon = require('sinon');
    sinonChai = require('sinon-chai');
    chai = require('chai');
    global.should = chai.should();
    global.expect = chai.expect;
    chai.should();
    chai.use(sinonChai);
    WildberryPrincess = require('../build/wildberry_princess').WildberryPrincess;
  } else {
    WildberryPrincess = window.WildberryPrincess;
    sinon = window.sinon;
  }

  describe('WildberryPrincess', function() {
    var ga_spy, item, jQuery, key, payload, transaction, transaction_id, value, wbp;
    jQuery = jQuery || null;
    wbp = ga_spy = null;
    transaction_id = transaction = item = key = value = payload = null;
    beforeEach(function() {
      window.ga = function() {};
      ga_spy = sinon.spy(window, 'ga');
      return wbp = new WildberryPrincess();
    });
    it('should contruct without issue', function() {
      return wbp.should.be.an["instanceof"](WildberryPrincess);
    });
    it('should have known functions', function() {
      wbp.should.itself.to.respondTo('trackUserActions');
      wbp.should.itself.to.respondTo('clickHandler');
      wbp.should.itself.to.respondTo('trackEvent');
      return wbp.should.itself.to.respondTo('sendPayload');
    });
    describe('#trackUserActions', function() {
      var wbp_spy;
      wbp_spy = null;
      beforeEach(function() {
        var button;
        wbp_spy = sinon.spy(wbp, 'trackUserActions');
        button = document.createElement('button');
        button.textConent = 'First Button';
        button.setAttribute('data-event-label', 'First Button');
        return document.body.appendChild(button);
      });
      it('should add data and click handlers to the elements', function() {
        var event_data;
        wbp.trackUserActions('button', 'Buttons');
        wbp_spy.should.have.been.calledOnce;
        event_data = document.querySelector('button').data;
        event_data.should.have.property('eventParams');
        return event_data.eventParams.should.have.keys('category', 'action');
      });
      return it('should add label and value data when supplied', function() {
        var event_data;
        wbp.trackUserActions('button', 'Buttons', 'Click', 'Label', 1);
        wbp_spy.should.have.been.calledOnce;
        event_data = document.querySelector('button').data;
        event_data.should.have.property('eventParams');
        return event_data.eventParams.should.have.keys('category', 'action', 'label', 'value');
      });
    });
    describe('#clickHandler', function() {
      var button, wbp_click_spy, wbp_send_spy;
      wbp_click_spy = wbp_send_spy = button = null;
      beforeEach(function() {
        wbp_click_spy = sinon.spy(wbp, 'clickHandler');
        wbp_send_spy = sinon.spy(wbp, 'sendPayload');
        button = document.createElement('button');
        button.innerText = 'First Button';
        button.setAttribute('data-event-label', 'First Button');
        return document.body.appendChild(button);
      });
      it('should track clicks on elements', function() {
        var click_event;
        wbp.trackUserActions('button', 'Buttons');
        click_event = document.createEvent('HTMLEvents');
        click_event.initEvent('click', true, false);
        button.dispatchEvent(click_event);
        wbp_click_spy.should.have.been.calledOnce;
        wbp_send_spy.should.have.been.calledOnce;
        window.ga.should.have.been.calledOnce;
        payload = {
          eventCategory: 'Buttons',
          eventAction: 'Click',
          eventLabel: 'First Button',
          hitType: 'event'
        };
        return window.ga.should.have.been.calledWith('send', payload);
      });
      it('should not set a label unless it is provided', function() {
        var click_event;
        button.removeAttribute('data-event-label');
        wbp.trackUserActions('button', 'Buttons');
        click_event = document.createEvent('HTMLEvents');
        click_event.initEvent('click', true, false);
        button.dispatchEvent(click_event);
        wbp_click_spy.should.have.been.calledOnce;
        wbp_send_spy.should.have.been.calledOnce;
        window.ga.should.have.been.calledOnce;
        payload = {
          eventCategory: 'Buttons',
          eventAction: 'Click',
          hitType: 'event'
        };
        return window.ga.should.have.been.calledWith('send', payload);
      });
      it('should track clicks on elements with optional value', function() {
        var click_event;
        wbp.trackUserActions('button', 'Buttons', 'Click', null, 1);
        click_event = document.createEvent('HTMLEvents');
        click_event.initEvent('click', true, false);
        button.dispatchEvent(click_event);
        wbp_click_spy.should.have.been.calledOnce;
        wbp_send_spy.should.have.been.calledOnce;
        window.ga.should.have.been.calledOnce;
        payload = {
          eventCategory: 'Buttons',
          eventAction: 'Click',
          eventLabel: 'First Button',
          eventValue: 1,
          hitType: 'event'
        };
        return window.ga.should.have.been.calledWith('send', payload);
      });
      return it('should return when there is no event', function() {
        wbp.clickHandler();
        wbp_click_spy.should.have.been.calledOnce;
        wbp_send_spy.should.not.have.been.calledOnce;
        return window.ga.should.not.have.been.calledOnce;
      });
    });
    describe('#trackEvent', function() {
      var wbp_spy;
      wbp_spy = null;
      beforeEach(function() {
        return wbp_spy = sinon.spy(wbp, 'sendPayload');
      });
      it('should track the event', function() {
        wbp.trackEvent('a', 'b', 'c', 'd');
        payload = {
          eventCategory: 'a',
          eventAction: 'b',
          eventLabel: 'c',
          eventValue: 'd',
          hitType: 'event'
        };
        wbp_spy.should.have.been.calledOnce;
        wbp_spy.should.have.been.calledWith(payload);
        ga_spy.should.have.been.calledOnce;
        return ga_spy.should.have.been.calledWith('send', payload);
      });
      it('should track the event without a label', function() {
        wbp.trackEvent('a', 'b', null, 'd');
        payload = {
          eventCategory: 'a',
          eventAction: 'b',
          eventValue: 'd',
          hitType: 'event'
        };
        wbp_spy.should.have.been.calledOnce;
        wbp_spy.should.have.been.calledWith(payload);
        ga_spy.should.have.been.calledOnce;
        return ga_spy.should.have.been.calledWith('send', payload);
      });
      return it('should track the event without a value', function() {
        wbp.trackEvent('a', 'b', 'c');
        payload = {
          eventCategory: 'a',
          eventAction: 'b',
          eventLabel: 'c',
          hitType: 'event'
        };
        wbp_spy.should.have.been.calledOnce;
        wbp_spy.should.have.been.calledWith(payload);
        ga_spy.should.have.been.calledOnce;
        return ga_spy.should.have.been.calledWith('send', payload);
      });
    });
    describe('#trackPageView', function() {
      var wbp_spy;
      wbp_spy = null;
      beforeEach(function() {
        return wbp_spy = sinon.spy(wbp, 'sendPayload');
      });
      it('should track the page view', function() {
        wbp.trackPageView('a', 'b');
        payload = {
          page: 'a',
          title: 'b',
          hitType: 'pageview'
        };
        wbp_spy.should.have.been.calledOnce;
        wbp_spy.should.have.been.calledWith(payload);
        ga_spy.should.have.been.calledOnce;
        return ga_spy.should.have.been.calledWith('send', payload);
      });
      it('should track the page view without a page provided', function() {
        wbp.trackPageView(null, 'b');
        payload = {
          page: window.location.pathname,
          title: 'b',
          hitType: 'pageview'
        };
        wbp_spy.should.have.been.calledOnce;
        wbp_spy.should.have.been.calledWith(payload);
        ga_spy.should.have.been.calledOnce;
        return ga_spy.should.have.been.calledWith('send', payload);
      });
      return it('should track the page view without a title', function() {
        wbp.trackPageView('a', null);
        payload = {
          page: 'a',
          title: 'Mocha',
          hitType: 'pageview'
        };
        wbp_spy.should.have.been.calledOnce;
        wbp_spy.should.have.been.calledWith(payload);
        ga_spy.should.have.been.calledOnce;
        return ga_spy.should.have.been.calledWith('send', payload);
      });
    });
    describe('#sendPayload', function() {
      beforeEach(function() {
        transaction_id = "" + (Date.now());
        transaction = {
          id: transaction_id,
          affiliation: "Candy Kingdom",
          revenue: 123,
          shipping: '0',
          tax: '0'
        };
        return item = {
          id: transaction_id,
          name: 'b',
          category: 'a',
          price: 123,
          quantity: 1
        };
      });
      it('should send the payload when there is GA', function() {
        ga_spy.callCount.should.equal(0);
        wbp.trackEcommerce('clear');
        ga_spy.should.have.been.calledWith('ecommerce:clear');
        wbp.trackEcommerce('addTransaction', transaction);
        ga_spy.should.have.been.calledWith('ecommerce:addTransaction', transaction);
        wbp.trackEcommerce('addItem', item);
        ga_spy.should.have.been.calledWith('ecommerce:addItem', item);
        wbp.trackEcommerce('send');
        return ga_spy.should.have.been.calledWith('ecommerce:send');
      });
      return it('should not send the payload when there is no GA', function() {
        window.ga = null;
        ga_spy.callCount.should.equal(0);
        wbp.trackEcommerce('clear');
        ga_spy.should.not.have.been.calledOnce;
        wbp.trackEcommerce('addTransaction', transaction);
        ga_spy.should.not.have.been.calledOnce;
        wbp.trackEcommerce('addItem', item);
        ga_spy.should.not.have.been.calledOnce;
        wbp.trackEcommerce('send');
        return ga_spy.should.not.have.been.calledOnce;
      });
    });
    describe('#set', function() {
      beforeEach(function() {
        key = 'my-key';
        return value = 'my-value';
      });
      it('should set the key to the value when there is GA', function() {
        ga_spy.callCount.should.equal(0);
        wbp.set(key, value);
        ga_spy.should.have.been.calledOnce;
        return ga_spy.should.have.been.calledWith('set', key, value);
      });
      return it('should set the key to the value when there is GA', function() {
        window.ga = null;
        ga_spy.callCount.should.equal(0);
        wbp.set(key, value);
        return ga_spy.should.not.have.been.calledOnce;
      });
    });
    return describe('#sendPayload', function() {
      beforeEach(function() {
        return payload = {
          hitType: 'event',
          eventCategory: 'my-category',
          eventAction: 'my-action',
          eventLabel: 'my-label',
          eventValue: 'my-value'
        };
      });
      it('should send the payload when there is GA', function() {
        ga_spy.callCount.should.equal(0);
        wbp.sendPayload(payload);
        ga_spy.should.have.been.calledOnce;
        return ga_spy.should.have.been.calledWith('send', payload);
      });
      return it('should not send the payload when there is no GA', function() {
        window.ga = null;
        ga_spy.callCount.should.equal(0);
        wbp.sendPayload(payload);
        return ga_spy.should.not.have.been.calledOnce;
      });
    });
  });

}).call(this);
