language: node_js
node_js:
  - 0.12
  - 0.11
  - 0.10
  - iojs
  - iojs-v1.0.4
env:
  - CODECLIMATE_REPO_TOKEN=9ffe8abc7638fd859bf081174225ff9846ee5a476c8793bd4e8cc3ec90dae358
before_script:
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter
script:
  - npm test
  - istanbul instrument --output lib-cov wildberry_princess.js
  - istanbul cover _mocha -- test/*_spec.js -R spec
after_script:
  - cat coverage/lcov.info | codeclimate
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
addons:
  code_climate:
    repo_token: 9ffe8abc7638fd859bf081174225ff9846ee5a476c8793bd4e8cc3ec90dae358
