language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CODECLIMATE_REPO_TOKEN=9ffe8abc7638fd859bf081174225ff9846ee5a476c8793bd4e8cc3ec90dae358
before_install:
  - npm conf set strict-ssl false
script:
  - npm ci
  - npm test
after_script:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/codeclimate-test-reporter'
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 9ffe8abc7638fd859bf081174225ff9846ee5a476c8793bd4e8cc3ec90dae358
