// Generated by CoffeeScript 1.9.1
(function() {
  var WildberryPrincess,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  WildberryPrincess = (function() {
    function WildberryPrincess() {
      this.clickHandler = bind(this.clickHandler, this);
    }

    WildberryPrincess.prototype.trackUserActions = function(selector, category, action, label, value) {
      var elements, i, params, results;
      params = {
        category: category,
        action: action || 'Click'
      };
      if (label) {
        params.label = label;
      }
      if (value) {
        params.value = value;
      }
      elements = document.querySelectorAll(selector);
      i = 0;
      results = [];
      while (i < elements.length) {
        elements[i].data = {
          eventParams: params
        };
        elements[i].removeEventListener('click', this.clickHandler);
        elements[i].addEventListener('click', this.clickHandler, false);
        results.push(i++);
      }
      return results;
    };

    WildberryPrincess.prototype.clickHandler = function(event) {
      var element, eventParams, label, payload, ref;
      element = event.target;
      eventParams = (ref = element.data) != null ? ref.eventParams : void 0;
      if (!eventParams) {
        return;
      }
      if (!(label = eventParams.label)) {
        label = (function() {
          switch (event.target.nodeName.toLowerCase()) {
            case 'button':
            case 'tab':
            case 'a':
              return element.innerText;
            case 'input':
            case 'select':
            case 'textarea':
              return element.getAttribute('name');
            default:
              return element.innerText;
          }
        })();
      }
      label = label != null ? label.trim() : void 0;
      payload = {
        hitType: 'event',
        eventCategory: eventParams.category,
        eventAction: eventParams.action
      };
      if (label) {
        payload.eventLabel = label;
      }
      if (eventParams.value) {
        payload.eventValue = eventParams.value;
      }
      this.sendPayload(payload);
    };

    WildberryPrincess.prototype.trackEvent = function(category, action, label, value) {
      var payload;
      payload = {
        hitType: 'event',
        eventCategory: category,
        eventAction: action
      };
      if (label) {
        payload.eventLabel = label;
      }
      if (value) {
        payload.eventValue = value;
      }
      return this.sendPayload(payload);
    };

    WildberryPrincess.prototype.sendPayload = function(payload) {
      if (window.ga != null) {
        return window.ga('send', payload);
      }
    };

    return WildberryPrincess;

  })();

  (typeof exports !== "undefined" && exports !== null ? exports : window).WildberryPrincess = WildberryPrincess;

}).call(this);
